_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSD,",
    offsets = "0,",
    addresses = "0x18d70,",
    stride_status = "Success",
    stride = 80,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMULSD,VMULSD,",
    offsets = "0,8,",
    addresses = "0x18d91,0x18de7,",
    stride_status = "Success",
    stride = 16,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 16,
    unroll_factor = 2,
  },
  {
    group_size = 9,
    pattern = "LLLLLLLLL",
    opcodes = "VMOVSD,VMULSD,VMULSD,VFMSUB231SD,VMOVSD,VMOVSD,VMULSD,VMULSD,VFMSUB231SD,",
    offsets = "-56,-72,-64,-56,-40,-16,-32,-24,-16,",
    addresses = "0x18d87,0x18da8,0x18db2,0x18dbc,0x18dcc,0x18ddd,0x18e06,0x18e10,0x18e1a,",
    stride_status = "Success",
    stride = 80,
    memory_status = "Success",
    accessed_memory = 72,
    accessed_memory_nooverlap = 72,
    accessed_memory_overlap = 0,
    span = 64,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSD,VMOVSD,",
    offsets = "0,8,",
    addresses = "0x18d81,0x18dd6,",
    stride_status = "Success",
    stride = 16,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 16,
    unroll_factor = 2,
  },
  {
    group_size = 10,
    pattern = "SSSSSSSSSS",
    opcodes = "VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,",
    offsets = "-80,-72,-64,-56,-48,-40,-32,-24,-16,-8,",
    addresses = "0x18d78,0x18da3,0x18dad,0x18db7,0x18dc7,0x18dd1,0x18e01,0x18e0b,0x18e15,0x18e25,",
    stride_status = "Success",
    stride = 80,
    memory_status = "Success",
    accessed_memory = 80,
    accessed_memory_nooverlap = 80,
    accessed_memory_overlap = 0,
    span = 80,
    head = 80,
    unroll_factor = 10,
  },
}
