_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPD,VINSERTF128,",
    offsets = "-32,-16,",
    addresses = "0x83d1,0x83d6,",
    stride_status = "Success",
    stride = 32,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 32,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPD,VINSERTF128,",
    offsets = "-32,-16,",
    addresses = "0x837d,0x8383,",
    stride_status = "Success",
    stride = 32,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 32,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPD,VINSERTF128,",
    offsets = "-32,-16,",
    addresses = "0x83b6,0x83c1,",
    stride_status = "Success",
    stride = 32,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 32,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPD,VINSERTF128,",
    offsets = "-32,-16,",
    addresses = "0x83a1,0x83a6,",
    stride_status = "Success",
    stride = 32,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 32,
    unroll_factor = 1,
  },
  {
    group_size = 7,
    pattern = "LLLSSSS",
    opcodes = "VMOVSD,VMOVHPD,VMOVHPD,VMOVLPD,VMOVHPD,VMOVLPD,VMOVHPD,",
    offsets = "-80,-120,-40,-160,-120,-80,-40,",
    addresses = "0x8393,0x8398,0x83b1,0x83f5,0x83fd,0x8402,0x8407,",
    stride_status = "Success",
    stride = 160,
    memory_status = "Success",
    accessed_memory = 56,
    accessed_memory_nooverlap = 56,
    accessed_memory_overlap = 0,
    span = 128,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSD,",
    offsets = "0,",
    addresses = "0x836f,",
    stride_status = "Success",
    stride = 160,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPD,VINSERTF128,",
    offsets = "0,16,",
    addresses = "0x8358,0x8368,",
    stride_status = "Success",
    stride = 32,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 32,
    unroll_factor = 1,
  },
}
