_group = {
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "-32,-24,-16,-8,",
    addresses = "0xbc53,0xbc9b,0xbce3,0xbd2b,",
    stride_status = "Success",
    stride = 40,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 10,
    pattern = "LSLSLSLSLS",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "-40,-40,-32,-32,-24,-24,-16,-16,-8,-8,",
    addresses = "0xbc38,0xbc49,0xbc80,0xbc91,0xbcc8,0xbcd9,0xbd10,0xbd21,0xbd58,0xbd69,",
    stride_status = "Success",
    stride = 40,
    memory_status = "Success",
    accessed_memory = 80,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 40,
    span = 40,
    head = 40,
    unroll_factor = 1,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "-32,-24,-16,-8,",
    addresses = "0xbc4e,0xbc96,0xbcde,0xbd26,",
    stride_status = "Success",
    stride = 40,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 5,
    pattern = "LLLLL",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "-40,-32,-24,-16,-8,",
    addresses = "0xbc18,0xbc60,0xbca8,0xbcf0,0xbd38,",
    stride_status = "Success",
    stride = 40,
    memory_status = "Success",
    accessed_memory = 40,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 0,
    span = 40,
    head = 40,
    unroll_factor = 5,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVSD,",
    offsets = "0,",
    addresses = "0xbbf4,",
    stride_status = "Success",
    stride = 40,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 5,
    pattern = "LLLLL",
    opcodes = "ADDSD,ADDSD,ADDSD,ADDSD,ADDSD,",
    offsets = "-40,-32,-24,-16,-8,",
    addresses = "0xbc32,0xbc7a,0xbcc2,0xbd0a,0xbd52,",
    stride_status = "Success",
    stride = 40,
    memory_status = "Success",
    accessed_memory = 40,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 0,
    span = 40,
    head = 40,
    unroll_factor = 5,
  },
  {
    group_size = 5,
    pattern = "LLLLL",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "-40,-32,-24,-16,-8,",
    addresses = "0xbc25,0xbc6d,0xbcb5,0xbcfd,0xbd45,",
    stride_status = "Success",
    stride = 40,
    memory_status = "Success",
    accessed_memory = 40,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 0,
    span = 40,
    head = 40,
    unroll_factor = 5,
  },
  {
    group_size = 5,
    pattern = "LLLLL",
    opcodes = "MULSD,MULSD,MULSD,MULSD,MULSD,",
    offsets = "109803,109731,109659,109587,109515,",
    addresses = "0xbc3d,0xbc85,0xbccd,0xbd15,0xbd5d,",
    stride_status = "RIP based value",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 40,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 0,
    span = 296,
    head = 0,
    unroll_factor = 5,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVSD,",
    offsets = "0,",
    addresses = "0xbbf0,",
    stride_status = "Success",
    stride = 40,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
}
