_group = {
  {
    group_size = 5,
    pattern = "SSSSS",
    opcodes = "VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,",
    offsets = "464,936,1408,1880,-8,",
    addresses = "0x8bff,0x8c0c,0x8c19,0x8c25,0x8c70,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 40,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 0,
    span = 1896,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "0,",
    addresses = "0x8c75,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "0,",
    addresses = "0x8c4b,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 7,
    pattern = "LLLLLLL",
    opcodes = "VMULSD,VMOVSD,MOV,MOV,VMOVAPD,VMOVAPD,VMULSD,",
    offsets = "146964,129103,129363,129326,129131,129077,129158,",
    addresses = "0x8b24,0x8b61,0x8b7e,0x8bab,0x8c2d,0x8c43,0x8c5a,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 104,
    accessed_memory_nooverlap = 93,
    accessed_memory_overlap = 11,
    span = 17895,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 11,
    pattern = "LLLSLLLLLLL",
    opcodes = "MOV,MOV,MOV,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,MOV,CMP,",
    offsets = "312,304,296,344,368,376,384,392,400,320,328,",
    addresses = "0x8b19,0x8b2c,0x8b34,0x8b3c,0x8b54,0x8b69,0x8b85,0x8b98,0x8bbc,0x8bc5,0x8c7f,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 88,
    accessed_memory_nooverlap = 88,
    accessed_memory_overlap = 0,
    span = 112,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 5,
    pattern = "SSSSS",
    opcodes = "VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,",
    offsets = "-8,464,936,1408,1880,",
    addresses = "0x8b72,0x8b8e,0x8ba1,0x8bb2,0x8bcd,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 40,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 0,
    span = 1896,
    head = 0,
    unroll_factor = 5,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOV,",
    offsets = "0,",
    addresses = "0x8bd7,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
}
