_group = {
  {
    group_size = 8,
    pattern = "SSSSSSSS",
    opcodes = "VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,",
    offsets = "-32,-24,-16,-8,8,16,24,32,",
    addresses = "0x1ebaf,0x1ebbb,0x1ebc2,0x1ebd3,0x1ec73,0x1ec7f,0x1ec86,0x1ec97,",
    stride_status = "Success",
    stride = 80,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 72,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 13,
    pattern = "LLLLLLLLLLLLL",
    opcodes = "VMULSD,VMULSD,VMULSD,VMULSD,VMULSD,VMULSD,VMOVSD,VMULSD,VMULSD,VMULSD,VMULSD,VMULSD,VMULSD,",
    offsets = "-64,-48,-96,-88,-80,-16,0,-64,-24,-8,-56,-48,-40,",
    addresses = "0x1eb36,0x1eb3b,0x1eb40,0x1eb4d,0x1eb6c,0x1ebe6,0x1ebed,0x1ebf3,0x1ebfa,0x1ebff,0x1ec04,0x1ec11,0x1ec30,",
    stride_status = "Success",
    stride = 80,
    memory_status = "Success",
    accessed_memory = 104,
    accessed_memory_nooverlap = 88,
    accessed_memory_overlap = 16,
    span = 104,
    head = 88,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSD,VMOVSD,",
    offsets = "0,-8,",
    addresses = "0x1ebd8,0x1ebde,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSD,VMOVSD,",
    offsets = "-8,0,",
    addresses = "0x1eb00,0x1eb0c,",
    stride_status = "Success",
    stride = 16,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 16,
    unroll_factor = 2,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "VMULSD,VMOVSD,VMULSD,",
    offsets = "24,40,-24,",
    addresses = "0x1eb16,0x1eb20,0x1eb2b,",
    stride_status = "Success",
    stride = 80,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 24,
    accessed_memory_overlap = 0,
    span = 72,
    head = 0,
    unroll_factor = 1,
  },
}
