_group = {
  {
    group_size = 10,
    pattern = "LLLLLLLLLL",
    opcodes = "VMOVUPD,VMOVUPD,VSUBPD,VSUBPD,VMOVUPD,VSUBPD,VMOVUPD,VMOVUPD,VSUBPD,VSUBPD,",
    offsets = "-32,-96,-176,-112,32,-48,96,-160,16,-240,",
    addresses = "0x22212,0x22222,0x22233,0x22241,0x2224b,0x22255,0x2225f,0x22269,0x22273,0x22284,",
    stride_status = "Success",
    stride = 320,
    memory_status = "Success",
    accessed_memory = 640,
    accessed_memory_nooverlap = 400,
    accessed_memory_overlap = 240,
    span = 400,
    head = 400,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "VMOVSD,VMOVSD,VMOVHPD,",
    offsets = "8,24,0,",
    addresses = "0x221c6,0x221df,0x221e6,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 24,
    accessed_memory_overlap = 0,
    span = 32,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "VMOVHPD,VMOVSD,VMOVSD,",
    offsets = "0,24,8,",
    addresses = "0x22124,0x22158,0x22164,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 24,
    accessed_memory_overlap = 0,
    span = 32,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVHPD,VMOVHPD,",
    offsets = "32,16,",
    addresses = "0x2216b,0x22172,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 24,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "CMP,",
    offsets = "808,",
    addresses = "0x222a0,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 5,
    pattern = "SSSSS",
    opcodes = "VMOVUPD,VMOVUPD,VMOVUPD,VMOVUPD,VMOVUPD,",
    offsets = "-320,-256,-192,-128,-64,",
    addresses = "0x222e2,0x222ed,0x222f8,0x22303,0x2230a,",
    stride_status = "Success",
    stride = 320,
    memory_status = "Success",
    accessed_memory = 320,
    accessed_memory_nooverlap = 320,
    accessed_memory_overlap = 0,
    span = 320,
    head = 320,
    unroll_factor = 5,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "VMOVSD,VMOVHPD,VMOVSD,VMOVUPD,",
    offsets = "0,8,32,16,",
    addresses = "0x22189,0x221a8,0x221d4,0x221f9,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 40,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 0,
    span = 40,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "VMOVSD,VMOVUPD,VMOVUPD,",
    offsets = "32,16,0,",
    addresses = "0x2228e,0x222a8,0x222b3,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 40,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 0,
    span = 40,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "VMOVSD,VMOVSD,VMOVHPD,",
    offsets = "24,8,0,",
    addresses = "0x22140,0x2227d,0x2229a,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 24,
    accessed_memory_overlap = 0,
    span = 32,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVHPD,VMOVHPD,",
    offsets = "32,16,",
    addresses = "0x221b2,0x221b9,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 24,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVHPD,VMOVHPD,",
    offsets = "32,16,",
    addresses = "0x22151,0x22293,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 24,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "VMOVSD,VMOVSD,VMOVHPD,",
    offsets = "8,24,0,",
    addresses = "0x22194,0x221a1,0x221c0,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 24,
    accessed_memory_overlap = 0,
    span = 32,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVHPD,VMOVHPD,",
    offsets = "32,16,",
    addresses = "0x221ec,0x221fe,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 24,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "VMOVSD,VMOVHPD,VMOVUPD,VMOVSD,",
    offsets = "16,24,0,32,",
    addresses = "0x2214c,0x2215f,0x2217f,0x221ad,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 40,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 0,
    span = 40,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "VMOVSD,VMOVUPD,VMOVSD,VMOVHPD,",
    offsets = "32,16,0,8,",
    addresses = "0x22118,0x22131,0x22136,0x22147,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 40,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 0,
    span = 40,
    head = 0,
    unroll_factor = 1,
  },
}
