_group = {
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "VMOVSS,VMOVSS,VMOVSS,",
    offsets = "0,0,0,",
    addresses = "0x2a90,0x2afe,0x2b4a,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 12,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 8,
    span = 4,
    head = 0,
    unroll_factor = 3,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x2a37,",
    stride_status = "Success",
    stride = 16,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x2a32,",
    stride_status = "Success",
    stride = 16,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "VMOVSS,VMOVSS,VMOVSS,",
    offsets = "0,0,0,",
    addresses = "0x2a9b,0x2ad9,0x2b2b,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 12,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 8,
    span = 4,
    head = 0,
    unroll_factor = 3,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "VMOVSS,VMOVSS,VMOVSS,",
    offsets = "0,0,0,",
    addresses = "0x2a86,0x2aef,0x2b3b,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 12,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 8,
    span = 4,
    head = 0,
    unroll_factor = 3,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x2a45,",
    stride_status = "Success",
    stride = 16,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
}
